<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="<?= $this->url() ?>">
            <?= $this->config()->admin['title'] ?>
        </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <? foreach ($this->repositories() as $r): ?>
        <? if ($r['showable']): ?>
        <li>
            <a href="<?= $this->url($r['name'] . '/list') ?>">
                <?= $r['label']['plural'] ?>
            </a>
        </li>
        <? endif; ?>
        <? endforeach; ?>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-cog"></span>
              <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
              <li role="presentation" class="dropdown-header">Documentation</li>
            <li>
                <a href="<?= $this->url('repositories') ?>">
                    <span class="glyphicon glyphicon-cloud"></span>&emsp;Repositories
                </a>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>