Page: <?= $_['list']['paginator']['page'] ?>
<br />
Total: <?= $_['list']['paginator']['total'] ?>

<table>
    <thead>
        <tr>
            <th></th>
            <? foreach ($_['list']['results'][0] as $key => $value): ?>
            <th><?= $key ?></th>
            <? endforeach; ?>
        </tr>
    </thead>
    <? foreach ($_['list']['results'] as $entity): ?>
    <tr>
        <td>
            <a href="<?= 'delete/' . $entity['id'] ?>">
                X
            </a>
        </td>
        <? foreach ($entity as $key => $value): ?>
        <td>
            <? if (is_array($value)): ?>
            <a href="http://localhost/dummy2/dummy2/pub/<?= $value['url'] ?>" target="_blank">
                file
            </a>
            <? else: ?>
            <?= $value ?>
            <? endif; ?>
        </td>
        <? endforeach; ?>
    </tr>
    <? endforeach; ?>
</table>