<?= $this->render(
    '../app/views/repository/partials/breadcrumbs.phtml',
    array(
        'repository' => $_['repository'],
        'active' => 'Create'
    )
) ?>

<? if (isset($_['success']) && $_['success']): ?>

<p class="alert alert-success">
    Element created successfully!
</p>

<? else: ?>

<form role="form" enctype="multipart/form-data" method="POST">
    <?= $this->render(
        '../app/views/repository/partials/form.phtml',
        array(
            'repository' => $_['repository'],
            'entity' => $_['entity'],
            'error' => $_['error']
        )
    )?>
</form>

<? endif; ?>