<?= $this->render(
    '../app/views/repository/partials/breadcrumbs.phtml',
    array(
        'repository' => $_['repository'],
        'active' => 'Delete'
    )
) ?>

<?= $this->render('../app/views/repository/partials/tabs.phtml', array(
    'action' => 'delete',
    'repository' => $_['repository'],
    'entity' => $_['entity']
)) ?>

<br />

<? if (isset($_['success']) && $_['success']): ?>

<p class="alert alert-success">
    Element deleted successfully!
</p>

<? else: ?>

<p class="alert alert-danger">
    Do you really want to delete this element?
</p>

<form role="form" method="POST">
    <button class="btn btn-danger" type="submit">
        Delete
    </button>
</form>

<? endif; ?>