<?= $this->render(
    '../app/views/repository/partials/breadcrumbs.phtml',
    array(
        'repository' => $_['repository'],
        'active' => 'Edit'
    )
) ?>

<?= $this->render('../app/views/repository/partials/tabs.phtml', array(
    'action' => 'edit',
    'repository' => $_['repository'],
    'entity' => $_['entity']
)) ?>

<br />

<form role="form" enctype="multipart/form-data">
    <?= $this->render(
        '../app/views/repository/partials/form.phtml',
        array(
            'repository' => $_['repository'],
            'entity' => $_['entity']
        )
    )?>
</form>