<?= $this->render(
    '../app/views/repository/partials/breadcrumbs.phtml',
    array(
        'repository' => $_['repository']
    )
) ?>

<? if ($_['repository']['description']): ?>
<div class="well">
    <?= $_['repository']['description']?>
</div>
<? endif; ?>

<div>
    <div class="col-md-10">
        <form action="<?= $this->url(
            $_['repository']['name'] . '/list'
        ) ?>" method="GET">
            <div class="input-group">
                <input type="text" name="query"<? if ($_['query']): ?> value="<?= $_['query']?>"<? endif; ?> class="form-control" autocomplete="off" />
                       <input type="hidden" name="limit" value="<?= $_['limit'] ?>" />
                <input type="hidden" name="orderb" value="<?= $_['orderb'] ?>" />
                <input type="hidden" name="orderd" value="<?= $_['orderd'] ?>" />
                <? foreach ($_['filters'] as $filter => $value): ?>
                <input type="hidden" name="filters[<?= $filter ?>]" value="<?= $value ?>" />
                <? endforeach; ?>
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div><!-- /input-group -->
        </form>
    </div>
    <div class="col-md-2">
        <a hef="#">
            <span class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
                Add new
            </span>
        </a>
    </div>
</div>

<div style="clear: both"></div>

<? if (count($_['repository']['parents']) > 0): ?>
<br />
<div class="container">
    <strong>Filters:</strong>
    <? foreach ($_['repository']['fields'] as $field): ?>
    <? if ($field['type'] == 'foreign_key'): ?>
    &emsp;
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          <strong><?= $field['repository']['label']['singular'] ?>:</strong>
          <? if (isset($_['filters'][$field['name']])): ?>
          <? foreach ($field['options'] as $option): ?>
          <? if ($option['value'] == $_['filters'][$field['name']]): ?>
          <?= $option['option'] ?>
          <? endif; ?>
          <? endforeach; ?>
          <? else: ?>
          All
          <? endif; ?>
          <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li>
            <a href="<?= $this->url(
                $_['repository']['name'] . '/list',
                array(
                    'query'   => $_['query'],
                    'limit'   => $_['limit'],
                    'orderb'  => $_['orderb'],
                    'orderd'  => $_['orderd'],
                    'filters' => array()
                )
            ) ?>">
                All
            </a>
        </li>
        <li class="divider"></li>
        <li>
            <? foreach ($field['options'] as $option): ?>
            <a href="<?= $this->url(
                $_['repository']['name'] . '/list',
                array(
                    'query'   => $_['query'],
                    'limit'   => $_['limit'],
                    'orderb'  => $_['orderb'],
                    'orderd'  => $_['orderd'],
                    'filters' => array_merge(
                        $_['filters'],
                        array($field['name'] => $option['value'])
                    )
                )
            ) ?>">
                <?= $option['option'] ?>
            </a>
            <? endforeach; ?>
        </li>
      </ul>
    </div>
    <? endif; ?>
    <? endforeach; ?>
</div>
<? endif; ?>

<? if ($_['list']['paginator']['results'] == 0): ?>

<br />
<p class="alert alert-info">
    No results
</p>

<? else: ?>

<div class="pull-right">
    <ul class="pagination">
        <li class="disabled">
            <a href="#">
                Total results: <strong><?= $_['list']['paginator']['results'] ?></strong>
            </a>
        </li>
        <? if ($_['list']['paginator']['page']['current'] > 1): ?>
        <li>
            <a href="<?= $this->url(
                $_['repository']['name'] . '/list',
                array(
                    'page'   => $_['list']['paginator']['page']['current'] - 1,
                    'query'  => $_['query'],
                    'limit'  => $_['limit'],
                    'orderb' => $_['orderb'],
                    'orderd' => $_['orderd']
                )
            ) ?>">
                &laquo;
            </a>
        </li>
        <? else: ?>
        <li class="disabled"><a href="#">&laquo;</a></li>
        <? endif; ?>
        <? for($i=1; $i<=$_['list']['paginator']['page']['total']; $i++): ?>
        <li<? if ($_['list']['paginator']['page']['current'] == $i): ?> class="active"<? endif; ?>>
            <a href="<?= $this->url(
                $_['repository']['name'] . '/list',
                array(
                    'page'   => $i,
                    'query'  => $_['query'],
                    'limit'  => $_['limit'],
                    'orderb' => $_['orderb'],
                    'orderd' => $_['orderd']
                )
            )?>">
                <?= $i ?>
            </a>
        </li>
        <? endfor; ?>
        <? if ($_['list']['paginator']['page']['current'] < $_['list']['paginator']['page']['total']): ?>
        <li>
            <a href="<?= $this->url(
                $_['repository']['name'] . '/list',
                array(
                    'page'   => $_['list']['paginator']['page']['current'] + 1,
                    'query'  => $_['query'],
                    'limit'  => $_['limit'],
                    'orderb' => $_['orderb'],
                    'orderd' => $_['orderd']
                )
            ) ?>">
                &raquo;
            </a>
        </li>
        <? else: ?>
        <li class="disabled"><a href="#">&raquo;</a></li>
        <? endif; ?>
    </ul>
</div>

<br />
<div class="pull-left">
    <div class="btn-group">
        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
            <strong>Rows per page:</strong> <?= $_['limit'] ?> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <? for($i=10; $i<=100; $i+=10): ?>
            <li>
                <a href="<?= $this->url(
                    $_['repository']['name'] . '/list',
                    array(
                        'query'   => $_['query'],
                        'limit'   => $i,
                        'orderb'  => $_['orderb'],
                        'orderd'  => $_['orderd'],
                        'filters' => array()
                    )
                ) ?>">
                    <?= $i ?>
                </a>
            </li>
            <? endfor; ?>
        </ul>
    </div>
</div>

<div style="clear: both"></div>

<div class="table-responsive">
    <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <? foreach ($_['repository']['fields'] as $field): ?>
                <? if (!$field['list']) continue; ?>
                <th>
                    <? if ($field['sortable']): ?>
                    <a href="<?= $this->url(
                        $_['repository']['name'] . '/list',
                        array(
                            'query'  => $_['query'],
                            'limit'  => $_['limit'],
                            'orderb' => $field['name'],
                            'orderd' => 'asc'
                        )
                    ) ?>">
                        <?= $field['label'] ?>
                    </a>
                    <? else: ?>
                    <?= $field['label'] ?>
                    <? endif; ?>
                </th>
                <? endforeach; ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($_['list']['results'] as $entity): ?>
            <tr>
                <? foreach ($_['repository']['fields'] as $field): ?>
                <? if (!$field['list']) continue; ?>
                <td>
                    <? if ($field['type'] == 'foreign_key'): ?>
                    <? foreach ($field['options'] as $option): ?>
                    <? if ($option['value'] == $entity[$field['name']]): ?>
                    <a href="<?= $this->url(
                        $field['repository']['name'] . '/read/' . $option['value']
                    ) ?>">
                        <?= $option['option'] ?>
                    </a>
                    <? break; ?>
                    <? endif; ?>
                    <? endforeach; ?>
                    <? elseif ($field['type'] == 'file'): ?>
                    <a href="<?= $entity[$field['name']]['url'] ?>" target="_blank">
                        file
                    </a>
                    <? else: ?>
                    <?= $entity[$field['name']] ?>
                    <? endif; ?>
                </td>
                <? endforeach; ?>
                <td class="text-right span1">
                    <a href="<?= $this->url($_['repository']['name'] . '/read/' . $entity['id']) ?>">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>
                    &emsp;
                    <a href="<?= $this->url('') ?>">
                        <span class="glyphicon glyphicon-remove red"></span>
                    </a>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>

<? endif; ?>