<?= $this->render(
    '../app/views/repository/partials/breadcrumbs.phtml',
    array(
        'repository' => $_['repository'],
        'active' => 'Read'
    )
) ?>

<?= $this->render('../app/views/repository/partials/tabs.phtml', array(
    'action' => 'read',
    'repository' => $_['repository'],
    'entity' => $_['entity']
)) ?>

<br />

<table class="table table-bordered">
    <? foreach ($_['repository']['fields'] as $field): ?>
    <tr>
        <th><?= $field['label'] ?></th>
        <td>
            <?= $_['entity'][$field['name']] ?>
        </td>
    </tr>
    <? endforeach; ?>
</table>