<?= $this->render(
    '../app/views/repository/partials/breadcrumbs.phtml',
    array(
        'repository' => $_['repository'],
        'active' => 'Read'
    )
) ?>

<?= $this->render('../app/views/repository/partials/tabs.phtml', array(
    'action' => 'read',
    'repository' => $_['repository'],
    'entity' => $_['entity']
)) ?>

<br />

<table class="table table-bordered">
    <? foreach ($_['repository']['fields'] as $field): ?>
    <tr>
        <th><?= $field['label'] ?></th>
        <td>
            <? if ($field['type'] == 'file'): ?>
            
            <? if ($_['entity'][$field['name']]): ?>
            <a href="<?= $_['entity'][$field['name']]['url'] ?>" targe="_blank">
                Download
            </a>
            <? endif; ?>
            
            <? elseif ($field['type'] == 'foreign_key'): ?>
            
            <? foreach ($field['options'] as $option): ?>
            <? if ($option['value'] == $_['entity'][$field['name']]): ?>
            <a href="<?= $this->url(
                $field['repository']['name'] . '/read/' . $option['value']
            ) ?>">
                <?= $option['option'] ?>
            </a>
            <? break; ?>
            <? endif; ?>
            <? endforeach; ?>
            
            <? else: ?>
            
            <?= $_['entity'][$field['name']] ?>
            
            <? endif; ?>
        </td>
    </tr>
    <? endforeach; ?>
</table>