<ol class="breadcrumb">
    <li>
        <a href="<?= $this->url('') ?>">
            Home
        </a>
    </li>
    <? $parents = array() ?>
    <? foreach ($_['repository']['fields'] as $field): ?>
    <? if ($field['type'] == 'foreign_key'): ?>
    <? $parents[] = '<a href="' . $this->url($field['repository']['name'] . '/list') . '">' . $field['repository']['label']['plural'] . '</a>' ?>
    <? endif; ?>
    <? endforeach; ?>
    <? if (count($parents) > 0): ?>
    <li>
        <?= implode(', ', $parents) ?>
    </li>
    <? endif; ?>
    <? if (isset($_['active'])): ?>
    <li>
        <a href="<?= $this->url(
            $_['repository']['name'] . '/list'
        )?>">
            <?= $_['repository']['label']['plural'] ?>
        </a>
    </li>
    <li class="active">
        <?= $_['active'] ?>
    </li>
    <? else: ?>
    <li class="active">
        <?= $_['repository']['label']['plural'] ?>
    </li>
    <? endif; ?>
</ol>