<? foreach ($_['repository']['fields'] as $field): ?>
<div class="form-group">
    
    <label for="<?= $field['name'] ?>">
        <?= $field['label'] ?>
    </label>
    
    <? if ($field['description']): ?>
    <p><?= $field['description'] ?></p>
    <? endif; ?>
    
    <? if ($field['type'] == 'string'): ?>
    
    <input type="text" 
       class="form-control" 
       name="<?= $field['name'] ?>" 
       id="<?= $field['name'] ?>" 
       <? if (isset($_['entity'])): ?>value="<?= $_['entity'][$field['name']] ?>"<?endif?>
    />
    
    <? elseif ($field['type'] == 'primary_key'): ?>
    
    <? if (isset($_['entity'])): ?>
    <input type="text" 
        class="form-control" 
        id="<?= $field['name'] ?>" 
        value="<?= $_['entity'][$field['name']] ?>" 
        disabled 
    />
    <? endif; ?>
    
    <? elseif ($field['type'] == 'foreign_key'): ?>
    
    <select 
        class="form-control" 
        name="<?= $field['name'] ?>" 
        id="<?= $field['name'] ?>"
    >
        <option value="">
            -- Select a <?= $field['label'] ?> --
        </option>
        <? foreach ($field['options'] as $option): ?>
        <option 
            value="<?= $option['value'] ?>"
            <? if (isset($_['entity'])): ?>
            <? if ($_['entity'][$field['name']] == $option['value']): ?> selected<? endif; ?>
            <? endif; ?>
        >
            <?= $option['option'] ?>
        </option>
        <? endforeach; ?>
    </select>
    
    <? elseif ($field['type'] == 'file'): ?>
    
    <input type="file" 
       class="form-control" 
       name="<?= $field['name'] ?>" 
       id="<?= $field['name'] ?>"
    />
    
    <? elseif ($field['type'] == 'text'): ?>
    
    <textarea 
        class="form-control" 
        name="<?= $field['name'] ?>" 
        id="<?= $field['name'] ?>"
    ><? if (isset($_['entity'])): ?><?= $_['entity'][$field['name']] ?><? endif; ?></textarea>
    
    <? endif; ?>
    
    <? if ($field['required']): ?>
    <p class="text-right">
        <small>* required</small>
    </p>
    <? endif; ?>
    
</div>

<? endforeach; ?>

<button type="submit" class="btn btn-default">
    <? if (isset($_['entity'])): ?>
    Save
    <? else: ?>
    Create
    <? endif;?>
</button>