<? if (isset($_['error'])): ?>
<p class="alert alert-danger">
    <?= $_['error']['message'] ?>
</p>
<? endif; ?>

<? foreach ($_['repository']['fields'] as $field): ?>

<? $errors = isset($_['error']) ? $_['error']['fields'][$field['name']] : array() ?>

<div class="form-group<? if (count($errors) > 0): ?> has-error<? endif; ?>">
    
    <? if (array_key_exists($field['name'], $_['entity'])): ?>
    <label for="<?= $field['name'] ?>">
        <?= $field['label'] ?>
    </label>
    <? endif; ?>
    
    <? if ($field['description']): ?>
    <p><?= $field['description'] ?></p>
    <? endif; ?>
    
    <? if ($field['type'] == 'string'): ?>
    
    <input type="text" 
       class="form-control" 
       name="<?= $field['name'] ?>" 
       id="<?= $field['name'] ?>" 
       <? if (isset($_['entity'][$field['name']])): ?>value="<?= $_['entity'][$field['name']] ?>"<?endif?>
    />
    
    <? elseif ($field['type'] == 'primary_key'): ?>
    
    <? if (isset($_['entity'][$field['name']])): ?>
    <input type="text" 
        class="form-control" 
        id="<?= $field['name'] ?>" 
        value="<?= $_['entity'][$field['name']] ?>" 
        disabled 
    />
    <? endif; ?>
    
    <? elseif ($field['type'] == 'foreign_key'): ?>
    
    <select 
        class="form-control" 
        name="<?= $field['name'] ?>" 
        id="<?= $field['name'] ?>"
    >
        <option value="">
            -- Select a <?= $field['label'] ?> --
        </option>
        <? foreach ($field['options'] as $option): ?>
        <option 
            value="<?= $option['value'] ?>"
            <? if (isset($_['entity']) && $_['entity']): ?>
            <? if ($_['entity'][$field['name']] == $option['value']): ?> selected<? endif; ?>
            <? endif; ?>
        >
            <?= $option['option'] ?>
        </option>
        <? endforeach; ?>
    </select>
    
    <? elseif ($field['type'] == 'file'): ?>
    
    <input type="file" 
       class="form-control" 
       name="<?= $field['name'] ?>" 
       id="<?= $field['name'] ?>"
    />
    
    <? elseif ($field['type'] == 'text'): ?>
    
    <textarea 
        class="form-control" 
        name="<?= $field['name'] ?>" 
        id="<?= $field['name'] ?>"
    ><? if (isset($_['entity'][$field['name']])): ?><?= $_['entity'][$field['name']] ?><? endif; ?></textarea>
    
    <? elseif ($field['type'] == 'boolean'): ?>
    
    <select 
        class="form-control" 
       name="<?= $field['name'] ?>" 
       id="<?= $field['name'] ?>"
    >
        <option value="0">
            No
        </option>
        <option value="1"<? if (isset($_['entity'][$field['name']])): ?>selected="selected"<?endif?>>
            Yes
        </option>
    </select>
    
    <? elseif ($field['type'] == 'date'): ?>
    
    <input type="date" 
       class="form-control" 
       name="<?= $field['name'] ?>" 
       id="<?= $field['name'] ?>" 
       <? if (isset($_['entity'][$field['name']])): ?>value="<?= $_['entity'][$field['name']] ?>"<?endif?>
    />
    
    <? elseif ($field['type'] == 'integer'): ?>
    
    <input type="number" 
       class="form-control" 
       name="<?= $field['name'] ?>" 
       id="<?= $field['name'] ?>" 
       <? if (isset($_['entity'][$field['name']])): ?>value="<?= $_['entity'][$field['name']] ?>"<?endif?>
    />
    
    <? endif; ?>
    
    <? if ($field['required']): ?>
    <p class="text-right">
        <small>* required</small>
    </p>
    <? endif; ?>
    
    <? if (isset($_['error'])): ?>
    <ul class="red">
        <? foreach ($_['error']['fields'][$field['name']] as $error): ?>
        <li>
            <?= $error ?>
        </li>
        <? endforeach; ?>
    </ul>
    <? endif; ?>
    
</div>

<? endforeach; ?>

<button type="submit" class="btn btn-default">
    <? if (isset($_['entity']['id'])): ?>
    Save
    <? else: ?>
    Create
    <? endif;?>
</button>