<ul class="nav nav-tabs">
    <li<? if ($_['action'] == 'read'): ?> class="active"<? endif; ?>>
        <a href="<?= $this->url(
            $_['repository']['name'] . '/read/' . $_['entity']['id']
        ) ?>">
            <span class="glyphicon glyphicon-eye-open"></span>
            Read
        </a>
    </li>
    <li<? if ($_['action'] == 'edit'): ?> class="active"<? endif; ?>>
        <a href="<?= $this->url(
            $_['repository']['name'] . '/edit/' . $_['entity']['id']
        ) ?>">
            <span class="glyphicon glyphicon-edit"></span>
            Edit
        </a>
    </li>
    
    <li<? if ($_['action'] == 'delete'): ?> class="active"<? endif; ?>>
        <a href="<?= $this->url(
            $_['repository']['name'] . '/delete/' . $_['entity']['id']
        ) ?>">
            <span class="glyphicon glyphicon-remove red"></span>
            Delete
        </a>
    </li>
    
    <? foreach ($_['repository']['children'] as $child): ?>
    <? $fieldName = $_['repository']['name'] . '_id' ?>
    <li>
        <a href="<?= $this->url(
            $child['repository'] . '/list',
            array(
                'filters' => array(
                    $fieldName => $_['entity']['id']
                )
            )
        ) ?>">
            <span class="glyphicon glyphicon-list"></span>
            <?= $child['label']['plural'] ?>
        </a>
    </li>
    <? endforeach; ?>
</ul>